# Generated by Django 3.1.3 on 2023-12-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20231213_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_check',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
